### PR TITLE
[Ref][Networking] Remove certain networking classes from netbase 

### PR DESCRIPTION
**Pull request by empinel**
**THIS PULL REQUEST IS ONLY FOR REFERENCE ONLY (AND FOR CODE INSPECTION) - NOT MEANT TO BE MERGED STANDALONE, INSTEAD LOOK AT PR #71**

#### What is the purpose of this pull request (PR)?

As stated in title

#### Any background context to help the reviewer?

In accordance with https://github.com/bitcoin/bitcoin/commit/21e5b96ff417f304e624052f629e2b030984180f

#### Was this PR tested and how?

On Ubuntu 16.04.01

#### Does this PR resolve an open issue (reference issue #)?

Fixes issue or JIRA tasks:

#

#### More Questions:

- Does the knowledge base need an update? No

- Does this PR add or change dependencies? No

- Does this PR change or fork the blockchain No

### CODE REVIEW

**Comment by AmirAbrams** [comment]
utACK.  I need to build the Windows version before merging.

**Comment by empinel** [comment]
Don't merge this itself, you can merge the branch https://github.com/SilkNetwork/Silk-Core/tree/venTriquilism

**Comment by SCDeveloper** [comment]
utACK - Simple splitting of function from file to new file. Can be merged.

**Comment by spencerlievens** [comment]
ACK - Build tested.

**Pull request merged**
