### PR TITLE
[C++][Core] Add compilance to C++11 Standards

### PR DESCRIPTION
**Pull request by empinel**
#### What is the purpose of this pull request (PR)?

Comply to C++11 Standards

#### Any background context to help the reviewer?

Not needed (although there is still a couple warnings (auto_ptr is depreciated) which need looking at)

#### Was this PR tested and how?

On Ubuntu 16.04 (64-bit) on VMWare Fusion

#### Does this PR resolve an open issue (reference issue #)?

Fixes issue or JIRA tasks: N/A

#

#### More Questions:

- Does the knowledge base need an update? Yes

- Does this PR add or change dependencies? No

- Does this PR change or fork the blockchain No

### CODE REVIEW

**Comment by empinel** [comment]
```
libsilk_wallet.a(libsilk_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
```

Clues?

**Comment by AmirAbrams** [comment]
In src/walletdb.cpp, try this:
```
#define BOOST_NO_CXX11_SCOPED_ENUMS
#include <boost/filesystem.hpp>
#undef BOOST_NO_CXX11_SCOPED_ENUMS
```
[stackoverflow.com](http://stackoverflow.com/questions/35007134/c-boost-undefined-reference-to-boostfilesystemdetailcopy-file)

**Comment by empinel** [comment]
Umm... that commit doesn't do it! I'll keep it open (got exams so still inactive)

**Comment by GregoryBetz** [comment]
tested ACK

I think this can be merged. Any objections?

**Pull request merged**
